### ISSUE TITLE
static!?

### ISSUE THREAD

**Issue by AlphaBeth** [CrazyChris3310/Lab7#1]
https://github.com/CrazyChris3310/Lab7/blob/adfcfaef751d81ecb4bb17e347eae6905d14c483/Server/src/main/java/utilities/dataBase/DataBaseConnection.java#L13-L15

**Comment by dushyntSharma** [comment]
If you are making them static then you need to assign values to them like hostName = something;
Try with that!

**Comment by dushyntSharma** [comment]
private static String hostName = somthing; 
 private static String hostPassword = something; 
 private static String URL = "jdbc:postgresql://pg:5432/";
